class CarData {
  static const Map<String, List<String>> brands = {
    'Abarth': ['595', '695', '124 Spider'],
    'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Giulietta', 'Mito', '159', '147', '156', 'GT', 'Brera', '4C'],
    'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'E-Tron', 'TT', 'R8', 'RS3', 'RS6', 'S3', 'S5'],
    'Aston Martin': ['DBX', 'Vantage', 'DBS', 'DB11', 'Rapide', 'Vanquish'],
    'Acura': ['NSX', 'MDX', 'RDX', 'TLX', 'Integra'],
    'Alpine': ['A110'],
    'Anadol': ['A1', 'A2', 'STC-16', 'P2'],
    'BMW': ['1 Serisi', '2 Serisi', '3 Serisi', '4 Serisi', '5 Serisi', '6 Serisi', '7 Serisi', '8 Serisi', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'iX', 'M2', 'M3', 'M4', 'M5', 'M8'],
    'Bentley': ['Bentayga', 'Continental GT', 'Flying Spur'],
    'Bugatti': ['Chiron', 'Veyron', 'Divo'],
    'Buick': ['Encore', 'Enclave', 'Regal'],
    'BYD': ['Atto 3', 'Han', 'Tang', 'Seal', 'Dolphin'],
    'Chevrolet': ['Aveo', 'Cruze', 'Captiva', 'Camaro', 'Corvette', 'Spark', 'Trax', 'Kalos', 'Lacetti', 'Rezzo', 'Tahoe', 'Suburban'],
    'Citroen': ['C3', 'C3 Aircross', 'C4', 'C4 X', 'C5 Aircross', 'C-Elysee', 'Berlingo', 'Ami', 'C1', 'C2', 'C5', 'C6', 'C8', 'Nemo', 'Saxo', 'Xsara', 'Jumper'],
    'Cadillac': ['Escalade', 'XT4', 'XT5', 'CT4', 'CT5', 'CTS'],
    'Chrysler': ['300C', 'Pacifica', 'Voyager', 'Crossfire'],
    'Cupra': ['Formentor', 'Leon', 'Ateca', 'Born'],
    'Chery': ['Omoda 5', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'Tiggo 4 Pro'],
    'Dacia': ['Sandero', 'Sandero Stepway', 'Duster', 'Jogger', 'Spring', 'Lodgy', 'Logan', 'Dokker', 'Solenza'],
    'Dodge': ['Challenger', 'Charger', 'Durango', 'Ram', 'Nitro', 'Journey'],
    'DS': ['DS 3', 'DS 4', 'DS 7 Crossback', 'DS 9', 'DS 5'],
    'Daewoo': ['Lanos', 'Matiz', 'Nubira', 'Nexia', 'Tico'],
    'Daihatsu': ['Terios', 'Sirion', 'Cuore', 'Materia', 'Copen'],
    'DFSK': ['Seres 3'],
    'Ferrari': ['488', '812', 'F8', 'Roma', 'SF90', 'Portofino', '458 Italia', 'F430', 'California', 'Purosangue'],
    'Fiat': ['Egea', 'Egea Cross', '500', '500L', '500X', 'Panda', 'Fiorino', 'Doblo', 'Linea', 'Punto', 'Albea', 'Palio', 'Uno', 'Tipo', 'Tempra', 'Bravo', 'Brava', 'Marea', 'Stilo', 'Sedici', 'Fullback'],
    'Ford': ['Fiesta', 'Focus', 'Puma', 'Kuga', 'Mustang', 'Mondeo', 'C-Max', 'B-Max', 'EcoSport', 'Ranger', 'Transit', 'Courier', 'Ka', 'Fusion', 'S-Max', 'Galaxy', 'Explorer', 'F-150', 'Taunus', 'Escort'],
    'Fisker': ['Ocean'],
    'Force': ['Gurkha'],
    'Genesis': ['G70', 'G80', 'GV70', 'GV80'],
    'GMC': ['Sierra', 'Yukon', 'Terrain', 'Canyon'],
    'Geely': ['Emgrand', 'Atlas', 'Coolray'],
    'Great Wall': ['Ora', 'Wey', 'Poer', 'Haval'],
    'Honda': ['Civic', 'City', 'Accord', 'HR-V', 'CR-V', 'Jazz', 'NSX', 'e', 'S2000', 'Integra', 'Prelude', 'Legend'],
    'Hyundai': ['i10', 'i20', 'i30', 'Elantra', 'Bayon', 'Kona', 'Tucson', 'Santa Fe', 'Ioniq 5', 'Ioniq 6', 'Getz', 'Accent Blue', 'Accent Era', 'Accent', 'Matrix', 'Sonata', 'Coupe', 'H-100', 'Staria'],
    'Hummer': ['H2', 'H3', 'EV'],
    'Haval': ['Jolion', 'H6'],
    'Infiniti': ['Q30', 'Q50', 'QX50', 'QX70', 'FX35', 'G35'],
    'Isuzu': ['D-Max'],
    'Iveco': ['Daily'],
    'Jaguar': ['XE', 'XF', 'XJ', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type', 'S-Type', 'X-Type'],
    'Jeep': ['Renegade', 'Compass', 'Grand Cherokee', 'Wrangler', 'Avenger', 'Gladiator', 'Cherokee', 'Patriot'],
    'JMC': ['Vigus'],
    'Kia': ['Picanto', 'Rio', 'Stonic', 'Ceed', 'XCeed', 'Niro', 'Sportage', 'Sorento', 'EV6', 'EV9', 'Cerato', 'Venga', 'Stinger', 'Soul', 'Sorento', 'Bongo'],
    'Koenigsegg': ['Jesko', 'Regera', 'Gemera'],
    'Lada': ['Niva', 'Vesta', 'Samara', 'Vega', 'Kalina'],
    'Land Rover': ['Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Defender', 'Discovery', 'Discovery Sport', 'Freelander'],
    'Lamborghini': ['Aventador', 'Huracan', 'Urus', 'Gallardo', 'Murcielago', 'Revuelto'],
    'Lexus': ['ES', 'LS', 'UX', 'NX', 'RX', 'RZ', 'LC', 'IS', 'GS'],
    'Lincoln': ['Navigator', 'Aviator', 'Continental'],
    'Lotus': ['Emira', 'Evija', 'Eletre', 'Elise', 'Exige'],
    'Lancia': ['Ypsilon', 'Delta', 'Thema', 'Kappa'],
    'Leapmotor': ['T03'],
    'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'Grecale', 'MC20', 'GranTurismo'],
    'Mazda': ['Mazda 2', 'Mazda 3', 'Mazda 6', 'CX-3', 'CX-30', 'CX-5', 'MX-5', 'RX-8', '323', '626'],
    'McLaren': ['720S', 'Artura', 'GT', '570S', 'P1'],
    'Mercedes-Benz': ['A-Serisi', 'B-Serisi', 'C-Serisi', 'E-Serisi', 'S-Serisi', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Serisi', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'Vito', 'Sprinter', 'Citan', 'X-Class', 'SLK', 'CLK'],
    'Mini': ['Cooper', 'Clubman', 'Countryman', 'Paceman'],
    'Mitsubishi': ['Space Star', 'Colt', 'ASX', 'Eclipse Cross', 'L200', 'Pajero', 'Attrage', 'Lancer', 'Carisma'],
    'MG': ['ZS', 'ZS EV', 'HS', 'MG4', 'Marvel R', 'Electric'],
    'Mahindra': ['Thar', 'XUV700'],
    'Nissan': ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Ariya', 'Navara', 'Note', 'Pulsar', 'Skyline', '350Z', '370Z', 'GT-R', 'Primera', 'Almera', 'Terrano'],
    'Nio': ['ET5', 'ET7', 'ES6', 'ES8'],
    'Opel': ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Grandland', 'Insignia', 'Adam', 'Combo', 'Zafira', 'Vectra', 'Tigra', 'Meriva', 'Antara'],
    'Peugeot': ['208', '308', '408', '508', '2008', '3008', '5008', 'Rifter', 'Partner', '106', '206', '207', '307', '407', '607', 'RCZ', 'Bipper'],
    'Porsche': ['911', '718 Boxster', '718 Cayman', 'Taycan', 'Panamera', 'Macan', 'Cayenne'],
    'Pagani': ['Huayra', 'Utopia', 'Zonda'],
    'Proton': ['Gen-2', 'Savy', 'Waja'],
    'Pontiac': ['Firebird', 'GTO'],
    'Renault': ['Clio', 'Taliant', 'Megane', 'Megane E-Tech', 'Captur', 'Austral', 'Koleos', 'Zoe', 'Symbol', 'Fluence', 'Kadjar', 'Scenic', 'Kangoo', 'Laguna', 'Latitude', 'Twizy', 'Modus', 'Safrane', 'R9', 'R11', 'R12', 'R19', 'R21'],
    'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan', 'Spectre'],
    'Rover': ['25', '45', '75', '200', '400', '600'],
    'Rivian': ['R1T', 'R1S'],
    'Rimac': ['Nevera'],
    'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Toledo', 'Altea', 'Cordoba'],
    'Skoda': ['Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Yeti', 'Rapid', 'Felicia', 'Roomster'],
    'Smart': ['Fortwo', 'Forfour', '#1'],
    'SsangYong': ['Korando', 'Musso', 'Torres', 'Tivoli', 'Kyron', 'Actyon'],
    'Subaru': ['Impreza', 'XV', 'Forester', 'Solterra', 'BRZ', 'Legacy', 'Outback'],
    'Suzuki': ['Swift', 'Ignis', 'Vitara', 'Jimny', 'S-Cross', 'Alto', 'Splash', 'Liana'],
    'Saab': ['9-3', '9-5'],
    'Skywell': ['ET5'],
    'Seres': ['Seres 3'],
    'Tata': ['Vista', 'Indigo', 'Safari', 'Telcoline'],
    'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X', 'Cybertruck'],
    'Tofaş': ['Şahin', 'Doğan', 'Kartal', 'Murat 124', 'Murat 131'],
    'Togg': ['T10X', 'T10F'],
    'Toyota': ['Yaris', 'Corolla', 'C-HR', 'Rav4', 'Land Cruiser', 'Hilux', 'Proace City', 'Supra', 'Auris', 'Avensis', 'Verso', 'Camry', 'Prius'],
    'TVR': ['Griffith', 'Sagaris'],
    'Volkswagen': ['Polo', 'Golf', 'T-Roc', 'Tiguan', 'Passat', 'Arteon', 'Taigo', 'Touareg', 'ID.3', 'ID.4', 'ID.5', 'Jetta', 'Scirocco', 'Caddy', 'Amarok', 'Crafter', 'Transporter', 'Beetle', 'Vento', 'Bora', 'CC', 'EOS'],
    'Volvo': ['S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'EX30', 'EX90', 'C30', 'C70', 'S40', 'S70', 'S80'],
    'Vauxhall': ['Corsa', 'Astra', 'Insignia', 'Mokka'],
    'Voyah': ['Free'],
    'Xpeng': ['P7', 'G9'],
    'Yamaha': ['OX99-11'],
    'Zenvo': ['TSR-S', 'ST1'],
    'Zotye': ['Nomad'],
  };
}
